ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS address VARCHAR(300),
  ADD COLUMN IF NOT EXISTS building_name VARCHAR(180),
  ADD COLUMN IF NOT EXISTS house_number VARCHAR(80),
  ADD COLUMN IF NOT EXISTS owner_name VARCHAR(180),
  ADD COLUMN IF NOT EXISTS owner_mobile VARCHAR(32),
  ADD COLUMN IF NOT EXISTS deposit NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS furnishing VARCHAR(80),
  ADD COLUMN IF NOT EXISTS maintenance_charges NUMERIC(12,2);

CREATE INDEX IF NOT EXISTS idx_properties_address ON properties(address);
